repos:
-   repo: https://github.com/ambv/black
    rev: 22.10.0
    hooks:
    - id: black
      language_version: python3
-   repo: local
    hooks:
    - id: eslint
      name: eslint
      entry: bash -c "cd frontend && npx eslint --fix 'src/**/*.vue'"
      language: node